### ISSUE TITLE
How to host this extension?

### ISSUE THREAD

**Issue by BobTB** [sn-extensions/action-bar#1]
How can I start this node.js app? 
What is the app startup file? 

I just want this to host on my server, to be able to use on the self hosted Standard Notes docker container I am running (which is working great BTW) - link here: https://hub.docker.com/r/bobthebuilder3tb/test/

I was trying to make it work as a standalone node.js app, which I then call through extensions link in the standard notes web client, but am unable to make it run, it complains about missing document or window, seems like it is missing something to work (most probably my knowledge is missing). 
Seems like folder/file structure is not correct if just copied as it is not.

**Comment by atmoio** [comment]
Hey, these are not yet ready to be self-hosted. I'm finishing up refactoring all the editors into components, and then plan on releasing some documentation. This is what I'm actively working on now and hope to be done with some time this week.

But in the mean time, these are not node apps. The non-editor components are all angular apps, but that's irrelevant. All you would need to do is host the index.html file somewhere, and make sure the scripts it's importing are at a valid location. Then it should just work.

**Comment by BobTB** [comment]
oh :) ok. Thank you for explaining! Now I understand.

**Comment by BobTB** [comment]
Seem some work has been done, is this close to being workable?

**Comment by atmoio** [comment]
Well, the only thing missing is proper documentation. But again the best way to host this is just getting this package extracted on your server and linking to the index.html file.

**Comment by BobTB** [comment]
I tried, hosted on https, entered the correct link, but all the editors do is open up empty, with no note data. I can enter text, edit it etc, but it does not save. If I swithc back to the plain editor, everything orginially in the note is still there, but no new data is saved

**Comment by atmoio** [comment]
Can you share the link you're using so I can test it? Feel free to email/slack me.
