### ISSUE TITLE
Action bar in Bold and Plus Editor counts characters in source, not rendered text

### ISSUE THREAD

**Issue by leafcutterant** [sn-extensions/action-bar#11]
If you use the Action Bar in the Bold Editor or the Plus Editor (may apply to other ones I don't know about), the character and word count is based on the HTML source. This makes Standard Notes unfit to do volume-constrained work if you need text formatting. The expected behavior is to base these metrics on the rendered text.

E.g. if you apply a hyperlink to a word, the character count in the Acton Bar increases, while in practice your text didn't become any longer.

Thanks for looking into this!

**Comment by JaspalSuri** [comment]
Thanks for letting me know! I will report this over to team!

**Comment by atmoio** [comment]
This is a known issue without a solution just yet.

**Comment by ningsongshen** [comment]
Just discovered a plugin for the Bold Editor that provides character counting: https://imperavi.com/redactor/plugins/counter/

**Comment by atmoio** [comment]
Would prefer not to have it always visible though..
