### ISSUE TITLE
Action bar taking up a lot of space on SN 2.1+.

### ISSUE THREAD

**Issue by ryanpcmcquen** [sn-extensions/action-bar#2]
I have uninstalled and reinstalled this extension and cleared all site data. The bar takes up a ton of space on the bottom, before 2.1 it did not.
![screenshot 1519857456](https://user-images.githubusercontent.com/772937/36817382-d1675008-1c95-11e8-8936-532625fd3c0c.png)

**Comment by atmoio** [comment]
Yeah..just introduced this bug with the last push today. Will fix this tomorrow.

**Comment by ryanpcmcquen** [comment]
Phew, I'm not going crazy!

**Comment by atmoio** [comment]
Should be fixed now

**Comment by ryanpcmcquen** [comment]
Looking much better.
