### ISSUE TITLE
Time/Date Format // ISO

### ISSUE THREAD

**Issue by drhus** [sn-extensions/action-bar#22]
I noticed the action-bar time and date format is 
Month/Date/Year, Hour:Minute AM/PM , The Month/Date and Date/Month is always confusing.. unless you will add an option to customize it, can't we just use ISO? YYYY-MM-DDThh:mmTZD  instead! or the local format of browser/pc etc

**Comment by JaspalSuri** [comment]
Hi @drhus, I apologize for the late response. I appreciate the feedback and will forward it over to the dev team for review. 🙂
