### ISSUE TITLE
White-space

### ISSUE THREAD

**Issue by russtypinn** [sn-extensions/action-bar#3]
Application of any non-default theme results in these white boxes. (SN Desktop 2.1.33)

Titanium:
![image](https://user-images.githubusercontent.com/26914332/41254509-881a1b72-6d78-11e8-908e-c86c3a66a738.png)

Focus:
![image](https://user-images.githubusercontent.com/26914332/41254674-041b07d6-6d79-11e8-8f4c-a4d9a17bcee7.png)

**Comment by russtypinn** [comment]
Resolved by uninstalling and reinstalling Action Bar 🤷‍♂️

**Comment by atmoio** [comment]
Yeah the screenshots above indicate an older version, so the uninstall must have refreshed that. The autoupdate for extensions isn't perfect yet, and requires the Extensions menu to be opened.
